
server:  port: 9091
  servlet:    context-path: /
    
spring:  application:    name: hystrix-books-service
    
eureka:  client:
    fetch-registry: true
    register-with-eureka: true    service-url:
      defaultZone: http://localhost:8080/eureka 
   
#开启hystrix熔断器
feign:
  hystrix:
    enabled: true
    
    
    